name: bie_daalt
description: Flutter onboarding and UI feature demo
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^3.1.12
  google_fonts: ^6.1.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/flutter_logo.png
